# Generated by Django 5.2.8 on 2026-02-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthMap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medservice',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='medservice',
            name='number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
