# Generated by Django 5.2.8 on 2026-02-28 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthMap', '0002_alter_medservice_email_alter_medservice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='selected_service',
            field=models.ForeignKey(blank=True, help_text='Medical service the user chose at the end of this session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_selections', to='HealthMap.medservice'),
        ),
        migrations.AddField(
            model_name='history',
            name='severity',
            field=models.CharField(blank=True, choices=[('non_emergency', 'Non Emergency'), ('moderate', 'Moderate Severity'), ('urgent', 'Urgent Care Needed')], help_text='Severity categorization assigned by AI during chat', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='medservice',
            name='accepts_insurance',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medservice',
            name='description',
            field=models.TextField(blank=True, help_text='General summary of the facility (size, focus area, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='medservice',
            name='google_rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Rating out of 5, e.g. 4.2', max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='medservice',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='medservice',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='medservice',
            name='payment_options',
            field=models.CharField(blank=True, help_text="e.g. 'Insurance, Cash, Payment Plan'", max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='medservice',
            name='services_offered',
            field=models.TextField(blank=True, help_text="Comma-separated list: e.g. 'Emergency, Radiology, Pediatrics'", null=True),
        ),
        migrations.AddField(
            model_name='medservice',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
