# Generated by Django 5.2.8 on 2026-02-28 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthMap', '0003_history_selected_service_history_severity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medservice',
            name='hours',
            field=models.CharField(blank=True, help_text="e.g. 'Mon-Fri 8am-6pm, Sat 9am-2pm, Sun Closed'", max_length=300, null=True),
        ),
    ]
